### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by jdeck88** [BNHM/reservemapper#1]
From michelle, download all results

**Comment by jdeck88** [comment]
implemented!
i had to work a bit to get to sort the behaviour of the download button.
Currently, the download button shows all the time but is disabled in the following conditions:
1) at the beginning of a session
2) if a user selects a new reserve to map
3) if the user selects clear

The download button only shows after a successful search and when all records finish loading.

one condition i wasn't sure what to do with: 
the user performs a query and presses "search" the button shows.  However, if the user starts typing a new search (e.g. changing a genus name). does the download button go away immediately?  What about the markers and table Text?  Since the markers and tableText don't go away immediately, i decided to leave the download button active.  This *could* be confusing if, for example, somewhat types a NEW genus but doesn't press "Search" again.  The download link, the markers, and tableText all show the OLD genus because the user hasn't yet pressed search. I think this is the desired behaviour but not sure.  

At any rate, i'm going to call this issue good and if anyone has strong feelings about how the behaviour of the download button should be changed, they can comment and re-open.

**Comment by mkoo** [comment]
Having the Download button present but disabled works well. It should be
available only if there is a dataset loaded up so the way you have it makes
sense.

I think if someone is redoing a query and forgets to hit Search, in the
future that may warrant some new user tip to show up but seems ok for now.

In fact, we may want hover tool tips for the three action buttons! i'll
file an issue....
