### ISSUE TITLE
incorporate CPAD API

### ISSUE THREAD

**Issue by mkoo** [BNHM/reservemapper#21]
https://gis.cnra.ca.gov/arcgis/rest/services/Boundaries

**Comment by jdeck88** [comment]
CPAD interface (calls their backend API): 
http://www.calands.org/map

Boundaries can be fetched from CPAD using their API, like this:

```
curl http://www.mapcollaborator.org/cpad/search/by_agency -d "agency_type=State&agency_name=University of California"
```
note that this bundles multiple Univ. California reserves into a single WKT file, so this file will need to be parsed. 

Can call reservemapper with this syntax:
```
http://reservemapper.berkeley.edu/{agency_type}/{agency_name}/{layer_name}
```
When a user calls with the above, the appropriate agency/name/layer_name is extracted from CPAD and displayed as the area of interest.... So, this task is enabling this syntax when calling reservemapper and zooming into the selected layer.

**Comment by jdeck88** [comment]
This is complete.
