### ISSUE TITLE
Reservemapper needs some TLC/ updates and broken icons

### ISSUE THREAD

**Issue by mkoo** [BNHM/reservemapper#45]
see the flagged updates needed. Also the up/down icons used in table are deprecated (or something)
see screenshot:

![Firefox_Screenshot_2020-08-12T20-17-27 964Z](https://user-images.githubusercontent.com/2523089/90063469-4a6fb600-dc9e-11ea-86fb-2ddd7111122a.png)

**Comment by jdeck88** [comment]
fixed with latest commit and deployed.
